languageCode = "en-us"
title = "Lischana Lane"
baseURL = "http://lischana-lane.co.uk/"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Lischana Lane"
	description = "Media Lecturer, Photographer and Filmmaker based in London"

	# The path must be relative to the static folder
	favicon = "https://s.gravatar.com/avatar/784dc9d50d2d4ef433dda5ceb6a68927?s=16"


	# Navigation
	[params.navigation]
		brand = "Lischana Lane"

		[params.navigation.links]
			about     = "About"
			services  = "Skillset"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Lischana Lane"
		subtitle   = "Media Lecturer, Photographer and Filmmaker based in London"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "About Lischana"
		description = "Lischana Lane (Far left) was awarded 2nd place for support staff of the year 2017 (North Warwickshire & Hinckley College), won the 2013 Vaughan award for best moving image (Birmingham Institute of Art & Design) and was runner up in the 2009 Harman photo Student Competition."
		buttonText  = "Get in touch!"


	# Service section
	[params.services]
		headline = "Skillset"

		[[params.services.list]]
				icon = "fa-graduation-cap"
				title = "Academic"
				description = "DTTLS, BA (Hons) Visual Communication, Diploma in Art & Design."

    [[params.services.list]]
        icon = "fa-camera"
        title = "Practical"
        description = "Digital photography & filmmaking. Location and studio, creative and commercial."

    [[params.services.list]]
				icon = "fa-desktop"
				title = "Technical"
				description = "Adobe Creative Cloud, Final Cut Pro and Aperture."

		[[params.services.list]]
				icon = "fa-handshake-o"
				title = "Human"
				description = "Using inclusivity, motivation and enthusiasm to provide engaging delivery."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Get In Touch!"
		description = "Contact me via Twitter or LinkedIn below!"
		twitter = "LVEL"
		linkedin = "https://www.linkedin.com/in/lischana-lane-7698a233/?ppe=1"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""

	[params.analytics]
		gaaccount = 'UA-96217691-1'
